# This is the config file of LoxCC.
#
# LoxCC compiles Lox source to C source, along with Lox C Runtime (LOXCRT)
# implementations. There's more than one C file, so a [outputFolderName] should be
# specified. LoxCC will output all related C files into this folder.
#
# If an [cc] is configured, LoxCC tries to compile the generated C source into
# binary.
#
# If compilation from C to binary is successful, C sources will be deleted if
# [deleteSourceAfterBuild] is set to true. If C compilation fails, C sources will be
# preserved whether [deteteSourceAfterBuild] is set or not.
#
# For readability, a formatter can be specified. As for clang-format, we need to pass "-i"
# to let it format in-place.

outputFolder: build
cc:
  path: gcc
  args: ["-O0", "-DGC_TRACE"]
  cleanUpSource: false
formatter:
  path: clang-format
  args: ["-i"]
