{{- /* Go Template */ -}}
{{- define "entrypoint" -}}

// AUTO GENERATED BY LOXCC -- DO NOT EDIT

#include "runtime/prelude.h"
#include "runtime/entrypoint.h"
#include "runtime/value.h"
#include "runtime/object.h"
#include "runtime/gc.h"
#include "runtime/table.h"

// Global var declarations
//
// Due to the limit of constant expressions, we can't place Lox expressions here to 
// initialize global variables; they'll be initialized in the entrypoint later.
{{- range .VarDecl }}
LRT_Value {{ template "mangle" .name }};
{{- end }}

void LRT_Entrypoint()
{
    // Global var definition (initialization)
    {{- range .VarDecl }}
    {{ template "mangle" .name }} = {{ .initializer }};
    {{- end}}

    // Main logic
    {{- range .Main }}
    {{ . }}
    {{- end }}
}

{{- end -}}