{{- /* Go Template */ -}}
{{- define "entrypoint" -}}

// AUTO GENERATED BY LOXCC -- DO NOT EDIT

#include "runtime/prelude.h"
#include "runtime/entrypoint.h"
#include "runtime/value.h"
#include "runtime/object.h"
#include "runtime/gc.h"
#include "runtime/table.h"
#include "runtime/native.h"

// Function declarations
//
// Lox supported first-class functions, which makes LoxCC use a LRT_Value to wrap a
// function pointer, and provide it as a (global) variable.
{{- range .Func }}
{{ template "funsig" . }}
{{- end }}

// Global var declarations
//
// Due to the limit of constant expressions, we can't place Lox expressions here to 
// initialize global variables; they'll be initialized in the entrypoint later.
//
// Native functions.
LRT_Value {{ template "mangle" "clock" }};
// User-defined functions.
{{- range .Func }}
LRT_Value {{ template "mangle" .name }};
{{- end}}
// Global variables.
{{- range .GlobalVar }}
LRT_Value {{ template "mangle" .name }};
{{- end }}

void LRT_Entrypoint()
{
    // Native functions.
    {{ template "mangle" "clock" }} = {{ template "fn" "clock" }};
    // Function var definition
    {{- range .Func }}
        {{- with .name }}
            {{ template "mangle" . }} = {{ template "fn" . }};
        {{- end }}
    {{- end }}
    // Global var definition (initialization)
    {{- range .GlobalVar }}
    {{ template "mangle" .name }} = {{ .initializer }};
    {{- end }}

    // Main logic
    {{- range .Main }}
    {{ . }}
    {{- end }}
}

// Function definitions
//
// Functions are implemented here. We don't implement them where they declared in order to
// avoid circular references.
{{- range .Func }}
{{ template "fundef" . }}
{{- end -}}

{{- end -}}