{{- /* Go Template */ -}}
{{- define "entrypoint" -}}

/* Auto generated by LoxCC -- DO NOT EDIT */

#include "runtime/prelude.h"
#include "runtime/entrypoint.h"
#include "runtime/value.h"
#include "runtime/object.h"
#include "runtime/gc.h"
#include "runtime/table.h"
#include <stdio.h>

void LRT_Entrypoint()
{
    LRT_Value value =
    {{- range .Main }}
    {{ . }}
    {{- end }}
    LRT_Print(value);
    printf("\n");
}

{{- end -}}