/* Auto generated by LoxCC -- DO NOT EDIT */

#include <stdio.h>
#include "runtime/prelude.h"
#include "runtime/entrypoint.h"
#include "runtime/value.h"
#include "runtime/object.h"
#include "runtime/gc.h"

void LRT_Entrypoint() {
    LRT_Value value = {{ . }};
    LRT_Print(value);
    printf("\n");
}