/* auto generated by LoxCC -- DO NOT EDIT */

#include "runtime/prelude.h"
#include "runtime/entrypoint.h"
#include "runtime/value.h"
#include "runtime/object.h"

void LRT_Entrypoint() {
    LRT_Value value = {{ . }};
    LRT_Print(value);
}