/* auto generated by LoxCC -- DO NOT EDIT */

#include "prelude.h"
#include "entrypoint.h"
#include "value.h"
#include "object.h"

void LRT_Entrypoint() {
    LRT_Value value = {{ . }};
    LRT_Print(value);
}